import boto3
# OPEN_AI_KEY = "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"
OPEN_AI_KEY = ""

ACCESS_SECRET_KEY = "PdsLJQpkYdFpx8us6n4S3unI9oSHruqHQ7iE5FMH"
ACCESS_KEY_ID = "AKIA47CRU24QLLPWELG2"
BUCKET_NAME = "lawyerdocsbucket"
